### ISSUE TITLE
novel data split can not be found

### ISSUE THREAD

**Issue by Gabriellamin** [frankaging/Reason-SCAN#2]
Hi,
The "A1 -novel color modifier" claims that test examples contains yellow square but training examples don't contain yellow square. However, I find that all combinations of color and shape can be found in the training set(p1-train, p2-train, p3-train). 

Could you tell me the possible reason? 

Thank you!

**Comment by frankaging** [comment]
Thanks for your interest in ReaSCAN. Sorry for the confusion about these namings of splits, but **p1-train/test, p2-train/test and p3-train/test should never be used to test compositionality** - their purposes are for testing whether having more clauses makes ReaSCAN harder (i.e., the top panel of Table 3 is what these sets are for).

The training set for testing compositionality is in `ReaSCAN-v1.1/ReaSCAN-compositional/data-compositional-splits.txt`. We have a bunch of unit tests which can be found here [verify_split_tests.ipynb](https://github.com/frankaging/Reason-SCAN/blob/main/code/dataset/verify_split_tests.ipynb) (and "yellow square" test is one of them, and see my attached screenshot below from this notebook file).

Please kindly close this issue if you find this helpful. Thanks again!

**Comment by frankaging** [comment]
![yellow,square](https://github.com/frankaging/Reason-SCAN/assets/15223704/bfa02899-4c95-4814-a94a-7284217ef7f1)

**Comment by Gabriellamin** [comment]
Thank you very much. I get it and it's very useful.
